# sonar-project.properties
sonar.projectKey=juice-shop-sast
sonar.projectName=Juice-shop-project
sonar.host.url=http://localhost:9000
sonar.token=sqp_24d133fa1556f24c8bfc230cb303dd755236206a
# Sources à analyser
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,**/test/**
# Langage principal
sonar.language=js
# Coverage (optionnel, si tests présents)
sonar.javascript.lcov.reportPaths=coverage/lcov.info